# Generated by Django 3.1.14 on 2022-06-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='Lat',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='Lon',
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='appears_at',
            field=models.DateTimeField(null=True, verbose_name='Appears at'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='disappears_at',
            field=models.DateTimeField(null=True, verbose_name='Disappears at'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Lon'),
        ),
    ]
